services:
  app:
    build: .
    ports:
      - "5746:5746"
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:5746
    volumes:
      - ./:/app
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - db
      - rabbitmq
      - redis
    deploy:
      resources:
        limits:
          memory: 512m
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: news_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
  redis:
    image: redis:7.4-alpine
  celery:
    build: .
    command: ./wait-for-it.sh rabbitmq:5672 -- celery -A news_api worker --loglevel=info --concurrency=2
    volumes:
      - ./:/app
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - app
      - db
      - rabbitmq
      - redis
    deploy:
      resources:
        limits:
          memory: 1024m  # Aumentado de 512m para 1024m
volumes:
  postgres_data: